# -*- coding: utf-8 -*-
zerrphix_first_install_post_populate = \
"""LOCK TABLES `ZP_PROCESS_RUN` WRITE;
/*!40000 ALTER TABLE `ZP_PROCESS_RUN` DISABLE KEYS */;
UPDATE `ZP_PROCESS_RUN` SET `ENABLED` = 1 ;
/*!40000 ALTER TABLE `ZP_PROCESS_RUN` ENABLE KEYS */;
UNLOCK TABLES;


LOCK TABLES `ZP_TEMPLATE` WRITE;
/*!40000 ALTER TABLE `ZP_TEMPLATE` DISABLE KEYS */;
INSERT INTO `ZP_TEMPLATE` VALUES (1,'Default','::template_path::',2,'2017-08-01 00:00:00');
/*!40000 ALTER TABLE `ZP_TEMPLATE` ENABLE KEYS */;
UNLOCK TABLES;
"""
